### ISSUE TITLE
Link to documentation is broken

### ISSUE THREAD

**Issue by vishalaj1** [graphfoundation/ongdb-documentation#2]
Hi,

I am trying to evaluate ongdb for my company and was trying to refer to documenation. However, link https://ongdb.graphfoundation.org/docs/ is broken.

We are trying to implement ongdb on aks and trying to find some documentation around this.

Can someone check this?

Regards,
Vishal

**Comment by bradnussbaum** [comment]
Hi @vishalaj1,

This project is in early stages of getting up and running. It's a work in progress and we hope to have it up soon. For anything in 3.x, you can reference the docs at https://neo4j.com/docs/ and you will find near complete compatibility. If something does not exist in ONgDB, just let us know and we will get it added.

Best,
Brad
